---
title: "Time-to-event data analysis with the bmstate package"
author: Juho Timonen
date: 3rd Nov 2025
output: 
  rmarkdown::html_vignette:
    toc: true 
    toc_depth: 3
    number_sections: true
    
bibliography: references.bib
editor: source
vignette: >
  %\VignetteIndexEntry{Time-to-event data analysis with the bmstate package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bmstate)
library(ggplot2)
theme_set(theme_bw())
```

Here we first simulate right-censored survival data and then go through 
the usual steps of a data analysis with the package.

## Simulating data

```{r}
tmax <- 10
h0_true <- 0.1 # true baseline hazard
beta_age_true <- 0.5 # true effect size of age
mod <- create_msm(transmat_survival(),
  hazard_covs = "age",
  tmax = tmax
)
simdat <- mod$simulate_data(w0 = h0_true, beta_haz = matrix(beta_age_true))
simdat$paths$plot_graph()
```

## Model setup: Setting knot locations

We set the spline knot locations based on quantiles of observed event times.

```{r}
event_times <- simdat$paths$transition_times()
mod$set_knots(t_max = tmax, t_event = event_times, num_knots = 4)
mod$get_knots()
```

## Fitting a model

```{r}
fit <- fit_stan(mod, simdat, chains = 1, adapt_delta = 0.975)
```

## Sampling diagnostics

```{r}
print(fit$info$diag)
```
```{r}
print(max(fit$info$summary$rhat))
```


## sd
